# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb967de06ca49b39ea14ff8cd311f9b8730bb2ecd78bb7232d38cc36718e61caf300fc4b0383e1b934aa0ac4d91d03931fdb59485823e0a0a300c08b378c4845

test:
  secret_key_base: 17b7efa61f6917600d65da555c4cb733651e7e6e7e0db1d59b6622b6981b7506ec1e69237059e8ed596d3eeabeeebea5ff0082bb959600367cd73c0f6fd85bdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
